env:
  browser: true
  es2021: true
  serviceworker: true
  jquery: true
extends:
  - "eslint:recommended"
  - "preact"
parserOptions:
  ecmaVersion: 12
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  indent:
   - "error"
   - 2
  semi:
   - "warn"
   - "always"
