title: LACKAWANNA EXPRESSO | DOTIN13'S BLOG
SEOTitle: DOTIN13'S BLOG
author: DotIN13
email: dotin13@126.com
description: "Act local, think global with DotIN13!"
show_excerpts: true # set to true to show excerpts on the homepage
url: "https://www.wannaexpresso.com"
avatar: "/img/orange.webp"

permalink: pretty
exclude: ["node_modules","package.json","README.md"]

# Gitalk settings
gitalk_clientid: false
# b4edc9ea059838b0bf4e

# Disqus settings
disqus_username: false

# Netease settings
netease_comment: false

# Valine settings
valine_appid: "PSy1tmiW2mx0DpKo7psk67EN-9Nh9j0Va"
valine_apikey: "MskLH2QYVC2Kqj8aG3XJ7x7o"

# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: DotIN13
  tagline: "LACKAWANNA<br>EXPRESSO"
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  navigation:
    - title: Home
      url: "/"
    - title: WoD
      url: "/wod"
    - title: About
      url: "/about"
  analytics_id: "UA-159368053-1"

  # generate social links in footer
  social_links:
    twitter: DotIN13
    github: DotIN13
    # linkedIn: in/thelehhman
    rss: rss
    # dribbble: jekyll
    facebook: peter.zhang.1466
    # weibo: DotIN13
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: DotIN13
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    telegram: DotIN13
    bilibili: 4471331
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-paginate-v2
#  - jekyll-seo-tag
#  - jekyll-feed

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################